FROM centos:8

RUN dnf install -y centos-release-stream \
  && dnf swap -y centos-{linux,stream}-repos \
  && dnf distro-sync -y

RUN dnf install -y tcsh epel-release \
    && dnf install -y gcc-c++ gcc-gfortran cmake wget subversion git make file xterm nano
